"""Constrained local runner for Python LeetCode-style solutions.

This is intentionally a small, dependency-free runner.  It isolates execution in
another interpreter, applies time/resource limits where the OS supports them, and
rejects common filesystem/network/process escape hatches.  It is not a security
boundary for untrusted third-party code; it is designed for code written by the
local user.
"""

from __future__ import annotations

import ast
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any


RESULT_MARKER = "__LEETTUTOR_RESULT__"
MAX_SOURCE_CHARS = 80_000
MAX_TEST_CHARS = 40_000
BLOCKED_MODULES = {
    "ctypes",
    "multiprocessing",
    "os",
    "pathlib",
    "shutil",
    "signal",
    "socket",
    "subprocess",
    "sys",
}
BLOCKED_CALLS = {
    "breakpoint",
    "compile",
    "eval",
    "exec",
    "exit",
    "getattr",
    "globals",
    "help",
    "input",
    "locals",
    "open",
    "quit",
    "setattr",
    "vars",
    "__import__",
}


@dataclass(frozen=True)
class RunResult:
    status: str
    summary: str
    stdout: str = ""
    stderr: str = ""
    duration_seconds: float = 0.0
    cases: tuple[dict[str, Any], ...] = ()

    @property
    def succeeded(self) -> bool:
        return self.status == "passed"

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "summary": self.summary,
            "stdout": self.stdout,
            "stderr": self.stderr,
            "duration_seconds": self.duration_seconds,
            "cases": list(self.cases),
        }


class CodeValidationError(ValueError):
    """Raised before user code is launched."""


def parse_test_cases(raw: str) -> list[dict[str, Any]]:
    """Parse one case object or an array of case objects."""

    if len(raw) > MAX_TEST_CHARS:
        raise CodeValidationError("测试用例过长，请控制在 40,000 字符以内。")
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise CodeValidationError(
            f"测试用例不是合法 JSON：第 {exc.lineno} 行第 {exc.colno} 列。"
        ) from exc
    cases = value if isinstance(value, list) else [value]
    if not cases:
        raise CodeValidationError("至少需要一个测试用例。")
    if len(cases) > 50:
        raise CodeValidationError("一次最多运行 50 个测试用例。")
    for index, case in enumerate(cases, start=1):
        if not isinstance(case, dict):
            raise CodeValidationError(f"第 {index} 个测试用例必须是 JSON 对象。")
        if "args" not in case:
            raise CodeValidationError(f"第 {index} 个测试用例缺少 `args`。")
        if not isinstance(case["args"], list):
            raise CodeValidationError(f"第 {index} 个测试用例的 `args` 必须是数组。")
        if "kwargs" in case and not isinstance(case["kwargs"], dict):
            raise CodeValidationError(f"第 {index} 个测试用例的 `kwargs` 必须是对象。")
    return cases


def validate_python_source(source: str) -> None:
    """Reject common dangerous operations while keeping algorithm libraries."""

    if not source.strip():
        raise CodeValidationError("请先写 Python 代码。")
    if len(source) > MAX_SOURCE_CHARS:
        raise CodeValidationError("代码过长，请控制在 80,000 字符以内。")
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        location = f"第 {exc.lineno} 行" if exc.lineno else ""
        raise CodeValidationError(f"Python 语法错误（{location}）：{exc.msg}") from exc

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            blocked = [alias.name for alias in node.names if alias.name.split(".")[0] in BLOCKED_MODULES]
            if blocked:
                raise CodeValidationError(f"本地练习运行器不允许导入：{', '.join(blocked)}")
        elif isinstance(node, ast.ImportFrom):
            module = (node.module or "").split(".")[0]
            if module in BLOCKED_MODULES:
                raise CodeValidationError(f"本地练习运行器不允许导入：{node.module}")
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id in BLOCKED_CALLS:
                raise CodeValidationError(f"本地练习运行器不允许调用 `{node.func.id}()`。")


def _resource_limiter() -> None:
    """Apply conservative Unix limits in the child process."""

    try:
        import resource

        memory = 512 * 1024 * 1024
        resource.setrlimit(resource.RLIMIT_AS, (memory, memory))
        resource.setrlimit(resource.RLIMIT_CPU, (4, 4))
        resource.setrlimit(resource.RLIMIT_FSIZE, (1_000_000, 1_000_000))
        resource.setrlimit(resource.RLIMIT_NOFILE, (16, 16))
    except (ImportError, OSError, ValueError):
        pass


def _harness(source: str, method_name: str, cases: list[dict[str, Any]]) -> str:
    return f'''# Generated by LeetTutor-Local.
from typing import *
from collections import Counter, defaultdict, deque
from functools import cache, lru_cache
import bisect
import heapq
import math

{source}

import json as _json
import time as _time

_CASES = _json.loads({json.dumps(json.dumps(cases, ensure_ascii=False))})
_METHOD = {json.dumps(method_name)}
_results = []
_started = _time.perf_counter()

try:
    _solution = Solution()
    if _METHOD:
        _callable = getattr(_solution, _METHOD)
    else:
        _names = [
            _name for _name in dir(_solution)
            if not _name.startswith("_") and callable(getattr(_solution, _name))
        ]
        if len(_names) != 1:
            raise ValueError(
                "无法自动判断要运行的方法，请填写方法名。候选：" + ", ".join(_names)
            )
        _METHOD = _names[0]
        _callable = getattr(_solution, _METHOD)

    for _index, _case in enumerate(_CASES, 1):
        _case_started = _time.perf_counter()
        _actual = _callable(*_case.get("args", []), **_case.get("kwargs", {{}}))
        _has_expected = "expected" in _case
        _passed = (not _has_expected) or _actual == _case["expected"]
        _results.append({{
            "case": _index,
            "passed": _passed,
            "actual": _actual,
            "expected": _case.get("expected"),
            "has_expected": _has_expected,
            "duration_ms": round((_time.perf_counter() - _case_started) * 1000, 3),
        }})
except BaseException as _exc:
    import traceback as _traceback
    _payload = {{
        "ok": False,
        "method": _METHOD,
        "error_type": type(_exc).__name__,
        "error": str(_exc),
        "traceback": _traceback.format_exc(),
        "cases": _results,
        "duration_seconds": _time.perf_counter() - _started,
    }}
else:
    _payload = {{
        "ok": all(_case["passed"] for _case in _results),
        "method": _METHOD,
        "cases": _results,
        "duration_seconds": _time.perf_counter() - _started,
    }}

print({json.dumps(RESULT_MARKER)} + _json.dumps(_payload, ensure_ascii=False, default=repr))
'''


def run_python_solution(
    *,
    source: str,
    method_name: str,
    test_cases: str,
    timeout_seconds: float = 3.0,
) -> RunResult:
    """Run a ``class Solution`` implementation against JSON cases."""

    validate_python_source(source)
    cases = parse_test_cases(test_cases)
    timeout = max(0.5, min(float(timeout_seconds), 10.0))
    script = _harness(source, method_name.strip(), cases)

    with tempfile.TemporaryDirectory(prefix="leettutor-run-") as temp_dir:
        script_path = Path(temp_dir) / "solution.py"
        script_path.write_text(script, encoding="utf-8")
        kwargs: dict[str, Any] = {
            "args": [sys.executable, "-I", "-S", str(script_path)],
            "cwd": temp_dir,
            "env": {"PYTHONIOENCODING": "utf-8", "PATH": os.defpath},
            "capture_output": True,
            "text": True,
            "timeout": timeout,
            "check": False,
        }
        if os.name == "posix":
            kwargs["preexec_fn"] = _resource_limiter
        try:
            completed = subprocess.run(**kwargs)  # noqa: S603
        except subprocess.TimeoutExpired as exc:
            stdout = (exc.stdout or "") if isinstance(exc.stdout, str) else ""
            return RunResult(
                status="timeout",
                summary=f"运行超过 {timeout:g} 秒，已自动停止。可能存在死循环或复杂度过高。",
                stdout=stdout[-12_000:],
                duration_seconds=timeout,
            )

    stdout = completed.stdout[-24_000:]
    stderr = completed.stderr[-12_000:]
    marker_index = stdout.rfind(RESULT_MARKER)
    if marker_index < 0:
        summary = "运行器没有收到结构化结果。"
        if completed.returncode < 0:
            summary += " 进程可能触发了资源限制。"
        return RunResult(
            status="error",
            summary=summary,
            stdout=stdout,
            stderr=stderr,
        )

    user_stdout = stdout[:marker_index].rstrip()
    try:
        payload = json.loads(stdout[marker_index + len(RESULT_MARKER) :].strip())
    except json.JSONDecodeError:
        return RunResult(
            status="error",
            summary="无法解析运行结果。",
            stdout=stdout,
            stderr=stderr,
        )

    duration = float(payload.get("duration_seconds", 0.0))
    result_cases = tuple(payload.get("cases", []))
    if payload.get("error"):
        return RunResult(
            status="error",
            summary=f"{payload.get('error_type', 'Error')}: {payload['error']}",
            stdout=user_stdout,
            stderr=str(payload.get("traceback", stderr))[-12_000:],
            duration_seconds=duration,
            cases=result_cases,
        )
    passed = bool(payload.get("ok"))
    passed_count = sum(bool(case.get("passed")) for case in result_cases)
    status = "passed" if passed else "failed"
    return RunResult(
        status=status,
        summary=f"{passed_count}/{len(result_cases)} 个测试通过",
        stdout=user_stdout,
        stderr=stderr,
        duration_seconds=duration,
        cases=result_cases,
    )
